'use client';

/**
 * Curated StoryOS icon set (MN-208). Line icons that read as software at any
 * size — the alternative to vendor emoji whose rendering we don't control.
 *
 * Stored on a database/space as `set:<name>` in the existing `icon` column.
 * As of #251 emoji are migrated away and no longer offered by the picker, but
 * the renderer still tolerates a stray legacy emoji string.
 *
 * The name/category/keyword *data* lives in @storyos/schemas (zod-free, so
 * apps/api and packages/mcp can use it for the emoji migration backfill and
 * MCP tool schemas without pulling in React). This file pairs each shared
 * name with its lucide-react component — the name is a stable slug decoupled
 * from the underlying library, so the geometry can be swapped for bespoke art
 * later without touching stored data.
 */
import {
  BRAND_ICON_META,
  BRAND_ICON_PREFIX,
  brandIconSlug,
  ICON_CATEGORIES,
  ICON_SET_META,
  ICON_SET_PREFIX,
  isBrandIconRef,
  isSetIconRef,
  setIconName,
  type BrandIconMeta,
  type IconCategory,
} from '@storyos/schemas';
import {
  Briefcase,
  FolderKanban,
  LayoutDashboard,
  Target,
  Rocket,
  Flag,
  Milestone,
  Trophy,
  Compass,
  Map,
  Building2,
  Goal,
  SquareCheck,
  CheckSquare,
  ListTodo,
  ListChecks,
  Clock,
  CalendarDays,
  CalendarClock,
  AlarmClock,
  Hourglass,
  Timer,
  Repeat,
  CircleDashed,
  Users,
  User,
  UserRound,
  UsersRound,
  Contact,
  Handshake,
  UserPlus,
  Crown,
  Baby,
  FileText,
  Files,
  Notebook,
  NotebookPen,
  BookOpen,
  Book,
  Newspaper,
  PenTool,
  Pencil,
  Feather,
  Image,
  Camera,
  Film,
  Clapperboard,
  Mic,
  Music,
  Palette,
  Brush,
  Database,
  Table,
  Table2,
  ChartBar,
  ChartLine,
  ChartPie,
  TrendingUp,
  Activity,
  Boxes,
  Package,
  Archive,
  Layers,
  Grid3x3,
  Filter,
  MessageSquare,
  MessageCircle,
  Mail,
  Send,
  Bell,
  Megaphone,
  Phone,
  AtSign,
  Hash,
  Wrench,
  Settings,
  Cog,
  Hammer,
  Bug,
  FlaskConical,
  TestTube,
  Link,
  Key,
  Lock,
  ShieldCheck,
  Zap,
  Plug,
  Puzzle,
  Wand,
  Sparkles,
  Gift,
  ShoppingCart,
  CreditCard,
  Receipt,
  DollarSign,
  Wallet,
  Coins,
  Tag,
  Tags,
  Bookmark,
  Paperclip,
  Pin,
  Star,
  Heart,
  Sprout,
  Leaf,
  TreePine,
  Flower2,
  Sun,
  Moon,
  Cloud,
  Waves,
  Flame,
  Droplet,
  Mountain,
  Snowflake,
  Bird,
  Home,
  Plane,
  Globe,
  MapPin,
  Coffee,
  CircleCheck,
  CircleAlert,
  CircleX,
  CircleDot,
  Circle,
  TriangleAlert,
  Ban,
  Eye,
  EyeOff,
  ThumbsUp,
  Loader,
  Pause,
  type LucideIcon,
} from 'lucide-react';

export type { IconCategory, BrandIconMeta };
export {
  BRAND_ICON_META,
  BRAND_ICON_PREFIX,
  brandIconSlug,
  ICON_CATEGORIES,
  ICON_SET_PREFIX,
  isBrandIconRef,
  isSetIconRef,
  setIconName,
};

export interface IconDef {
  name: string;
  Icon: LucideIcon;
  categories: IconCategory[];
  keywords: string;
}

/** Public path each brand SVG is vendored at (#298) — one file per
 * `BRAND_ICON_META` entry, named by slug. See apps/web/public/brand-icons/. */
export function brandIconSrc(slug: string): string {
  return `/brand-icons/${slug}.svg`;
}

/** Name → lucide-react component. The name/category/keyword data itself comes
 * from ICON_SET_META (@storyos/schemas) — this is only the rendering half. */
const ICON_COMPONENTS: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  'folder-kanban': FolderKanban,
  'layout-dashboard': LayoutDashboard,
  target: Target,
  rocket: Rocket,
  flag: Flag,
  milestone: Milestone,
  trophy: Trophy,
  compass: Compass,
  map: Map,
  building2: Building2,
  goal: Goal,
  'square-check': SquareCheck,
  'check-square': CheckSquare,
  'list-todo': ListTodo,
  'list-checks': ListChecks,
  clock: Clock,
  'calendar-days': CalendarDays,
  'calendar-clock': CalendarClock,
  'alarm-clock': AlarmClock,
  hourglass: Hourglass,
  timer: Timer,
  repeat: Repeat,
  'circle-dashed': CircleDashed,
  users: Users,
  user: User,
  'user-round': UserRound,
  'users-round': UsersRound,
  contact: Contact,
  handshake: Handshake,
  'user-plus': UserPlus,
  crown: Crown,
  baby: Baby,
  'file-text': FileText,
  files: Files,
  notebook: Notebook,
  'notebook-pen': NotebookPen,
  'book-open': BookOpen,
  book: Book,
  newspaper: Newspaper,
  'pen-tool': PenTool,
  pencil: Pencil,
  feather: Feather,
  image: Image,
  camera: Camera,
  film: Film,
  clapperboard: Clapperboard,
  mic: Mic,
  music: Music,
  palette: Palette,
  brush: Brush,
  database: Database,
  table: Table,
  table2: Table2,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  activity: Activity,
  boxes: Boxes,
  package: Package,
  archive: Archive,
  layers: Layers,
  grid3x3: Grid3x3,
  filter: Filter,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  mail: Mail,
  send: Send,
  bell: Bell,
  megaphone: Megaphone,
  phone: Phone,
  'at-sign': AtSign,
  hash: Hash,
  wrench: Wrench,
  settings: Settings,
  cog: Cog,
  hammer: Hammer,
  bug: Bug,
  'flask-conical': FlaskConical,
  'test-tube': TestTube,
  link: Link,
  key: Key,
  lock: Lock,
  'shield-check': ShieldCheck,
  zap: Zap,
  plug: Plug,
  puzzle: Puzzle,
  wand: Wand,
  sparkles: Sparkles,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  receipt: Receipt,
  'dollar-sign': DollarSign,
  wallet: Wallet,
  coins: Coins,
  tag: Tag,
  tags: Tags,
  bookmark: Bookmark,
  paperclip: Paperclip,
  pin: Pin,
  star: Star,
  heart: Heart,
  sprout: Sprout,
  leaf: Leaf,
  'tree-pine': TreePine,
  flower2: Flower2,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  waves: Waves,
  flame: Flame,
  droplet: Droplet,
  mountain: Mountain,
  snowflake: Snowflake,
  bird: Bird,
  home: Home,
  plane: Plane,
  globe: Globe,
  'map-pin': MapPin,
  coffee: Coffee,
  'circle-check': CircleCheck,
  'circle-alert': CircleAlert,
  'circle-x': CircleX,
  'circle-dot': CircleDot,
  circle: Circle,
  'triangle-alert': TriangleAlert,
  ban: Ban,
  eye: Eye,
  'eye-off': EyeOff,
  'thumbs-up': ThumbsUp,
  loader: Loader,
  pause: Pause,
};

export const ICON_SET: IconDef[] = ICON_SET_META.map((meta) => {
  const Icon = ICON_COMPONENTS[meta.name];
  if (!Icon) throw new Error(`icon-set.tsx: no lucide component registered for "${meta.name}".`);
  return { ...meta, Icon };
});

export const ICON_BY_NAME: Record<string, LucideIcon> = ICON_COMPONENTS;
